# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Green Coding  
email: chakib.belgaid@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  this is my personal blog where i put some technical articles and some other philosophical taughts .
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com



# Build settings
# theme: plainwhite
remote_theme: samarsault/plainwhite-jekyll
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plainwhite:
  name: Chakib Belgaid
  tagline: PHD Student in energy consumption of software
           "(33) 755 297-214"
  date_format: "%b %-d, %Y"

  social_links:
    twitter: chakib_med
    github: chakib-belgaid
    linkedIn: in/chakib-belgaid 
    facebook: chakib.med
    instagram: chakib.med 
    
  portfolio_image: "assets/portfolio.jpg"
  sitemap: true

  navigation:
    - title: My Work
      url: "/my-work"
    - title: Resume
      url: "/resume"